name = "ReferenceFiniteElements"
uuid = "6dc62d09-f8eb-43fd-9672-074e490a997f"
authors = ["Craig M. Hamel <cmhamel32@gmail.com> and contributors"]
version = "0.10.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Exodus = "f57ae99e-f805-4780-bdca-96e224be1e5a"

[extensions]
ReferenceFiniteElementsAdaptExt = ["Adapt"]
ReferenceFiniteElementsExodusExt = ["Exodus"]

[compat]
Adapt = "3"
Aqua = "0.8"
Distributions = "0.25"
DocStringExtensions = "0.9"
Exodus = "0.10"
FastGaussQuadrature = "0.5, 1"
ForwardDiff = "0.10"
JET = "0.8"
LinearAlgebra = "1"
Polynomials = "3, 4"
PrecompileTools = "1"
SpecialPolynomials = "0.4"
StaticArrays = "1"
StructArrays = "0.6"
Test = "1"
TestSetExtensions = "2"
julia = "1"

[extras]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Exodus = "f57ae99e-f805-4780-bdca-96e224be1e5a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Adapt", "Aqua", "Distributions", "Exodus", "ForwardDiff", "JET", "Test", "TestSetExtensions"]
